// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYFfV_O0-uaUSEAq0kN_CmUF1k5XEjMPM',
    appId: '1:429454810385:android:f05d4351b59e0b8d7f40b0',
    messagingSenderId: '429454810385',
    projectId: 'todo-database-d0b49',
    storageBucket: 'todo-database-d0b49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEcgpeahw5pywC3hUesmk1UqkKdD2dFWI',
    appId: '1:429454810385:ios:25e62a8a79e13f5b7f40b0',
    messagingSenderId: '429454810385',
    projectId: 'todo-database-d0b49',
    storageBucket: 'todo-database-d0b49.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM0c3cmlMV27KDmMRJ8M-nhGzcFM9zrcE',
    appId: '1:429454810385:web:51ef906556802e357f40b0',
    messagingSenderId: '429454810385',
    projectId: 'todo-database-d0b49',
    authDomain: 'todo-database-d0b49.firebaseapp.com',
    storageBucket: 'todo-database-d0b49.firebasestorage.app',
    measurementId: 'G-BFBF7QM239',
  );
}
